### ISSUE TITLE
Unable to use selector li:not(.D\(n\))

### ISSUE THREAD

**Issue by mayank-hey** [dperini/nwmatcher#102]
One of my project dependencies rely on your library for unit testing using no-browser selectors. After our dependency upgraded to 1.3.8 we have noticed an error in the unit tests. It is because we use a selector ``li:not(.D\(n\))`` to select all ``li`` elements that do not have class name ``D(n)``. After the upgraded we are getting error ``Unknown pseudo-class selector``

**Comment by dperini** [comment]
The only functional change in 1.3.8 was due to issue #101 so the problem must be related to that.
This is obviously an edge case having to do with escaped characters nested in the ":not()" selector.
I will have a look at the problem and maybe @mjgp2 (issue #101 submitter) is able to help here too.
Thank you for reporting.

**Comment by mjgp2** [comment]
I don't think that's a valid class name under the CSS grammar?

**Comment by mjgp2** [comment]
> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

**Comment by mjgp2** [comment]
Would seem that the regular expression cannot handle escaping perhaps.

**Comment by dperini** [comment]
@mjgp2 thank you for looking to this again ... however more requests for the escaping issue are becoming frequent (see request/answer https://github.com/tmpvar/jsdom/issues/1550 in "jsdom" repo above). It will not be easy nor very clean but I will listen to feedback and think about it again (time permitting).

**Comment by dperini** [comment]
Trying this in a browser like FF:

    document.querySelectorAll("li:not(.D\(n\))");

yeld the following error:

    Error: An invalid or illegal string was specified

So it seems the expression syntax is really invalid.
