### ISSUE TITLE
tag for 1.4.1 is missing

### ISSUE THREAD

**Issue by lddubeau** [dperini/nwmatcher#104]
The tag for 1.4.1, which is the latest release at the time of writing, is missing.

Among problems this causes: [cdnjs](https://cdnjs.com/libraries/nwmatcher) does not yet publish 1.4.1 because it is set to detect new versions of nwmatcher through git, which means it looks for tags and uses that.

**Comment by dperini** [comment]
This was easy to fix ...
Thank you for reporting the problem.

**Comment by lddubeau** [comment]
Thanks.
