### ISSUE TITLE
hasAttributes erroneously called on elements that do not support it

### ISSUE THREAD

**Issue by lddubeau** [dperini/nwmatcher#105]
### Versions

nwmatcher: 1.4.0, 1.4.1
Chrome: 59.0.3071.109
jsdom: 11.1.0

### Steps to reproduce

1. Open this [plunk](https://embed.plnkr.co/1zZHAw/). The plunk uses 1.4.0 but the issue occurs with 1.4.1 too.

2. Open the console and look at errors.

The relevant code is this:

```
var frag = document.createDocumentFragment();
frag.appendChild(document.createElement("div"));
frag.firstElementChild.innerHTML =
  "<input class=\"typeahead form-control\" type=\"text\">";
var input = frag.firstElementChild.firstElementChild;
NW.Dom.match(input, "foo[bar] .form-control");
```

### Expected results

No errors

### Actual results

```
nwmatcher.js:761 Uncaught TypeError: node.hasAttribute is not a function
    at Object.hasAttribute (nwmatcher.js:761)
    at Object.eval [as foo[bar] .form-control] (eval at compile (nwmatcher.js:1042), <anonymous>:3:178)
    at Object.match (nwmatcher.js:1448)
    at (index):12
```

### Discussion

The code above was refined from the sequence of instructions performed in a real application that has been in use for years without any trouble. The code in the real application uses a template to create a DOM tree that is then passed to the Twitter Typeahead plugin (through jQuery) to create a typeahead field. The DOM tree is then inserted into the actual document the user sees. This has worked fine in all major browsers out there. I use jsdom in the test suite. It worked fine in jsdom 8. The issue I'm reporting here surfaced when I upgraded from jsdom 8 to jsdom 11.1, which uses nwmatcher internally.

I suspect the problem is that nwmatcher finds the `input` element through a search for `.form-control` and then examines up the tree to determine whether the element is a descendant of `foo[bar]` and while doing this it tries to call `.hasAttribute` on a document fragment.

If I disconnect `input` from the fragment before calling `NW.Dom.match(input, "foo[bar] .form-control");`, the error does not occur.

**Comment by dperini** [comment]
Yes I acknowledge the bug exists, your explanation of it is also correct ...
While walking up the descendants the "bar" attribute is also checked and the problem reveals when the resolver reaches the "document fragment" which does not have an "hasAttribute" method, thus the error you noticed.

I already have the fix for this ... but I am on vacations, far away from my usual workplace.
Let's see what I can do from here.
Thank you for reporting this.
Your help is appreciated.

**Comment by dperini** [comment]
Landed a fix for the reported problem. Normalized and improved the DOM walking methods.
Could you please check & confirm your issue is resolved by this change ?

**Comment by lddubeau** [comment]
I confirm the the problem is gone. Thanks. I'll let you decide when the issue should be closed.
