### ISSUE TITLE
Support for the case insensitive attribute selector tag

### ISSUE THREAD

**Issue by papandreou** [dperini/nwmatcher#108]
For example:

```css
input[type="hidden" i] {
    display: none
}
```

I've run into this because this syntax is heavily used in [Chromium's default stylesheet](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css#412). I'm using this default stylesheet along with jsdom/nwmatcher to make sure that the font subsetting code in https://github.com/assetgraph/assetgraph picks up a reasonable set of default `font-family`/`font-weight`/`font-style` declarations for the given elements.

It's this syntax: https://drafts.csswg.org/selectors-4/#attribute-case

Apologies in advance if this is considered out of scope because it's defined in a draft spec.

**Comment by dperini** [comment]
In the new code branch of `nwmatcher` (named `nwsapi`) there is already support for this feature and other  Selectors Level 4 goodies.
I am currently evaluating the possibility to port these new features to the current `nwmatcher` branch. I am planning a preview release containing this feature end of next week.

**Comment by papandreou** [comment]
Very well, carry on, then ;-)
