### ISSUE TITLE
lastSlice is not defined in noqsa line 846

### ISSUE THREAD

**Issue by nrkn** [dperini/nwmatcher#109]
https://github.com/dperini/nwmatcher/blob/master/src/nwmatcher-noqsa.js#L846

Confirmed in both browser, and node.js+jsdom

This is the smallest I could get it down to:

```js
const el1 = document.createDocumentFragment()
const child1 = document.createElement( 'div' )
el1.appendChild( child1 )

const el2 = document.createElement( 'section' )
const child2 = document.createElement( 'p' )
el2.appendChild( child2 )

first( 'span', el1 )
first( 'span', el2 )
```

- throws `TypeError: lastSlice is undefined` on the second call to `first` - expected was returns `null`
- el1 must be a document fragment
- el1 and el2 must have at least one child
- the same selector must be used on both
- neither el2 nor the child elements' tagNames seem to matter
- the selector doesn't seem to matter

**Comment by dperini** [comment]
Acknowledge the bug ... thank you for reporting the issue.
A fix is on the way, also this bug did exist at least since 1.3.x so it was well hidden :)

**Comment by dperini** [comment]
Fixed ! Doing some test before pushing to `npm`.
Thank you again for reporting.
👍
