### ISSUE TITLE
isNative fooled by simple toString function

### ISSUE THREAD

**Issue by shimscharf** [dperini/nwmatcher#94]
var fakeNative = String(Object.prototype.toString).replace(/ \w+\(/, ' (');
var fn = function (){};
fn.toString = function (){return fakeNative}

isNative (fn)        // true, should be false

The way around this is to first test if the function has its own prototype, and that it's prototype is not of class object or undefined

function isType (obj) {
       return toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase()
}
hasOwn = function (obj, key) {
      return Object.prototype.hasOwnProperty.call(obj, key);
}

if (isType == "function" && hasOwn (obj, "prototype") && (isType(obj.prototype) == "object" || isType(obj.prototype) == "undefined")) {return false}
return isNative(method)

This works for ie6+ and all modern & mobile browsers
You can even leave out the isNative check, seems like the first logic sorts out all user functions/methods and the rest can be assumed to be native by default

**Comment by dperini** [comment]
@shimscharf,
I don't think this is an issue, out of testing :)
Yes, it is easy to fake these kind of checks. However nobody does that, no need.
Also the version used for node/jsdom and older IE browsers (nwmatcher-noqsa) doesn't use 'isNative'.

**Comment by dperini** [comment]
@shimscharf,
Just for reference and history ... you can read more about that same fooling here (2009):

    http://perfectionkills.com/detecting-built-in-host-methods/
overriding the toString method of the function to test, like you did.

**Comment by shimscharf** [comment]
Hi Diego,

Thank you for the reference, I have previously read it.

I was looking to see if anyone managed to get an almost foolproof way of 
simply differentiating between host object / function and user created 
ones. Mostly for use in my own deep clone/extend function. I ended up 
creating my own, that does a pretty good job, and fast.

Cheers,

Simon

**Comment by dperini** [comment]
@schimscharf,
I quickly tried this modified version with your fakeNative:

    var isNative = (function() {
        var re = / \w+\(/,
            native = String(Object.prototype.toString).replace(re, ' (');
        return function(method) {
            return !!method &&
                typeof method != 'string' &&
                Object.toString === method.toString &&
                native == String(method).replace(re, ' (');
        };
    })();

it seems to work, though I don't know our far it goes in being the perfect solution.
