### ISSUE TITLE
Searching for empty attributes in CSS selectors incorrectly matches missing attributes

### ISSUE THREAD

**Issue by stuartlangridge** [dperini/nwmatcher#95]
var jsdom = require("jsdom");
    var pageHTML = '<!doctype html><html><head></head><body><div></div><div title=""></div><div title="yes"></div></body></html>';

    jsdom.env({
        html: pageHTML,
        done: function(err, window) {
            console.log(window.document.querySelectorAll("div[title='']").length); // => 2 (wrong!)
            console.log(window.document.querySelectorAll("div[title][title='']").length); // => 1 (correct)
        }
    });

Note that a selector `div[title='']` should not match `<div>`, but here does.

(was originally https://github.com/tmpvar/jsdom/issues/1163)

**Comment by dperini** [comment]
@stuartlangridge
appreciate the heads up and the help with this issue.
The problem should be fixed for all browsers by commit https://github.com/dperini/nwmatcher/commit/26d7b36
